version: '3.9'

services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: palatine
      POSTGRES_PASSWORD: palatine
      POSTGRES_DB: palatine
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://palatine:palatine@db:5432/palatine
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    ports:
      - '4000:4000'

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '3000:3000'

volumes:
  dbdata:


